name: "cql"
replay_buffer_size: ${overrides.replay_buffer_size}
collector_type: "path"
model_dir: ${overrides.model_dir}

agent:
  _target_: rlkit.examples.algorithms.actor_critic.wrapper.SACAgent
  obs_dim: ???
  action_dim: ???
  max_q_learning: true                  # Use max Q learning for evaluation

  layer_size: 256
  num_hidden_layer: 3

algorithm_cfg:
  batch_size: 256
  max_path_length: 1000               # The maximum path length for exploration
  num_epochs: 3000                      # The main training epochs of an RL algorithm; not used in MPC-based algorithms
  num_eval_steps_per_epoch: 5000
  num_trains_per_train_loop: 1000        # this number // # expl steps per loop = # trains per expl step
  train_at_start: false
  min_num_steps_before_training: 1000    # No exploraion in offline RL
  save_snapshot_gap: 100
  timeout:

get_module_path: rlkit.examples.algorithms.actor_critic.cql.prepare_models_and_trainers
get_algo_path: rlkit.examples.algorithms.actor_critic.cql.prepare_generic_rl_algorithm
