name: "mbpo"
replay_buffer_size: ${overrides.replay_buffer_size}
collector_type: ${overrides.collector_type}
model_dir: ${overrides.model_dir}

eval_transition_model:      # true / false


agent:
  _target_: rlkit.examples.algorithms.actor_critic.wrapper.SACAgent
  discount: 1.0
  layer_size: ${overrides.layer_size}
  num_hidden_layer: ${overrides.num_hidden_layer}
  hidden_init: torch.nn.init.xavier_uniform_
  obs_dim: ???
  action_dim: ???

dynamics:
  _target_: ${overrides.dynamics._target_}
  ensemble_model: ${overrides.dynamics.ensemble_model}
  learn_reward: ${overrides.dynamics.learn_reward}
  separate_reward_func: ${overrides.dynamics.separate_reward_func}
  learn_logstd_min_max: ${overrides.dynamics.learn_logstd_min_max}
  learning_rate: ${overrides.dynamics.learning_rate}
  batch_size: ${overrides.dynamics.batch_size}
  num_elites: ${overrides.dynamics.num_elites}
  normalize_inputs: ${overrides.dynamics.normalize_inputs}

algorithm_cfg:
  batch_size: 32                      # Not used in MBPO
  max_path_length: 1000               # The maximum path length for exploration
  num_epochs: 400                     # The main training epochs of an RL algorithm
  num_eval_steps_per_epoch: 5000
  num_expl_steps_per_train_loop: 1000    # Each epoch can have multiple loops.. how many expl steps per loop
  num_trains_per_train_loop: 1000        # this number // # expl steps per loop = # trains per expl step
  num_train_loops_per_epoch: 1        # Another loop within each epoch (default=1)
  num_model_learning_epochs: ${overrides.dynamics.num_model_learning_epochs}       # Model learning epochs
  max_epochs_since_last_update: 5
  model_train_period: ${overrides.trainer_cfg.model_train_period}             # Number of steps until the next model training
  min_num_steps_before_training: 5000      # Initial exploration
  rand_init_policy_before_training: false  # Whether to use the random policy for initial exploration
  use_best_parameters: true          # Use the best model parameters using val loss (model learning & policy learning)
  eval_initial_policy: true
  save_snapshot_gap: 100
  initial_training_steps: 0
  timeout:

get_module_path: rlkit.examples.algorithms.actor_critic.mbpo.prepare_models_and_trainers
get_algo_path: rlkit.examples.algorithms.actor_critic.mbpo.prepare_generic_rl_algorithm
